sudo: required
services:
  - docker

before_install:
  - docker build -t manishsingh10895/docker-complex-client -f ./client/Dockerfile.dev ./client

script:
  - docker run manishsingh10895/docker-complex-client npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t manishsingh10895/docker-complex-client  ./client
  - docker build -t manishsingh10895/docker-complex-server  ./server
  - docker build -t manishsingh10895/docker-complex-work  ./worker
  - docker build -t manishsingh10895/docker-complex-nginx  ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manishsingh10895/docker-complex-client
  - docker push manishsingh10895/docker-complex-nginx
  - docker push manishsingh10895/docker-complex-server
  - docker push manishsingh10895/docker-complex-work
